project:
  type: website

website:
  title: "Si-Nguyen Mai"
  description: "Welcome to Si-Nguyen Mai's personal website."
  site-url: https://singuyenmai.github.io/
  repo-url: https://github.com/singuyenmai/singuyenmai.github.io
  navbar:
    right:
      # - text: "Projects"
        # href: index.qmd#projects
      - text: "Blog"
        href: blog.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/singuyenmai
      - icon: linkedin
        href: https://www.linkedin.com/in/si-nguyen-thu-mai/
      - icon: twitter
        href: https://twitter.com/SiNguyenMai
  
  open-graph:
    site-name: "Si-Nguyen Mai"
  twitter-card:
    creator: "@SiNguyenMai"
  cookie-consent: false

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
    highlight-style: atom-one
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    smooth-scroll: true
